-- CreateTable
CREATE TABLE "SystemSetting" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "elecRate" REAL NOT NULL DEFAULT 7.0,
    "waterRate" REAL NOT NULL DEFAULT 18.0,
    "waterMinUnit" REAL NOT NULL DEFAULT 5.0,
    "commonFee" REAL NOT NULL DEFAULT 0.0,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
